services:
  backend:
    build: ./server1
    ports:
      - 5000:5000
    # environment:
    #   - MONGO_URI=mongodb+srv://admin:admin@cluster0.zqzqx.mongodb.net/procurement?retryWrites=true&w=majority
    #   - JWT_SECRET=secret
    #   - JWT_EXPIRE=3600
    #   - PORT=5000
    #   - EMAIL_USER=your_email@example.com
    #   - EMAIL_PASSWORD=your_email_password
  frontend:
    build: ./procurement-system
    ports:
      - 5173:5173
      
